// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {repo} from '../models';
import {menu} from '../models';

export function ConnectNeo(arg1:main.Conn):Promise<void>;

export function GetEdgeList():Promise<{[key: string]: Array<repo.Edge>}>;

export function GetLookUp():Promise<{[key: string]: string}>;

export function HelpMenu(arg1:menu.CallbackData):Promise<void>;

export function IgnoreMe(arg1:repo.Edge):Promise<void>;
