// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectNeo(arg1) {
  return window['go']['main']['App']['ConnectNeo'](arg1);
}

export function GetEdgeList() {
  return window['go']['main']['App']['GetEdgeList']();
}

export function GetLookUp() {
  return window['go']['main']['App']['GetLookUp']();
}

export function HelpMenu(arg1) {
  return window['go']['main']['App']['HelpMenu'](arg1);
}

export function IgnoreMe(arg1) {
  return window['go']['main']['App']['IgnoreMe'](arg1);
}
